"""autogenerated by genpy from drrobot_clinicrobot/MotorCmd.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorCmd(genpy.Message):
  _md5sum = "83414dfe9e393966fab06f8909c63052"
  _type = "drrobot_clinicrobot/MotorCmd"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# wheel motor command message from DrRobot Robot.
int32 motorcmd1		# left motor encoder command value
int32 motorCmd2	        # right motor encoder Comamnd value
int32 motorCtrl		# motor ctrl method , 0-- PWM, 1-- velocity  2-- position


"""
  __slots__ = ['motorcmd1','motorCmd2','motorCtrl']
  _slot_types = ['int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       motorcmd1,motorCmd2,motorCtrl

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorCmd, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.motorcmd1 is None:
        self.motorcmd1 = 0
      if self.motorCmd2 is None:
        self.motorCmd2 = 0
      if self.motorCtrl is None:
        self.motorCtrl = 0
    else:
      self.motorcmd1 = 0
      self.motorCmd2 = 0
      self.motorCtrl = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3i.pack(_x.motorcmd1, _x.motorCmd2, _x.motorCtrl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.motorcmd1, _x.motorCmd2, _x.motorCtrl,) = _struct_3i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3i.pack(_x.motorcmd1, _x.motorCmd2, _x.motorCtrl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.motorcmd1, _x.motorCmd2, _x.motorCtrl,) = _struct_3i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3i = struct.Struct("<3i")
