// Generated by gencpp from file drrobot_clinicrobot/BumpSensor.msg
// DO NOT EDIT!


#ifndef DRROBOT_CLINICROBOT_MESSAGE_BUMPSENSOR_H
#define DRROBOT_CLINICROBOT_MESSAGE_BUMPSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drrobot_clinicrobot
{
template <class ContainerAllocator>
struct BumpSensor_
{
  typedef BumpSensor_<ContainerAllocator> Type;

  BumpSensor_()
    : header()
    , bump_sw1(0)
    , bump_sw2(0)
    , bump_sw3(0)
    , bump_sw4(0)  {
    }
  BumpSensor_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bump_sw1(0)
    , bump_sw2(0)
    , bump_sw3(0)
    , bump_sw4(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _bump_sw1_type;
  _bump_sw1_type bump_sw1;

   typedef uint8_t _bump_sw2_type;
  _bump_sw2_type bump_sw2;

   typedef uint8_t _bump_sw3_type;
  _bump_sw3_type bump_sw3;

   typedef uint8_t _bump_sw4_type;
  _bump_sw4_type bump_sw4;




  typedef boost::shared_ptr< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> const> ConstPtr;

}; // struct BumpSensor_

typedef ::drrobot_clinicrobot::BumpSensor_<std::allocator<void> > BumpSensor;

typedef boost::shared_ptr< ::drrobot_clinicrobot::BumpSensor > BumpSensorPtr;
typedef boost::shared_ptr< ::drrobot_clinicrobot::BumpSensor const> BumpSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drrobot_clinicrobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'drrobot_clinicrobot': ['/home/drrobot2/hokuyo_exp/src/drrobot_clinicrobot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "555b7e3f76b2263507508b9011bd9a1a";
  }

  static const char* value(const ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x555b7e3f76b22635ULL;
  static const uint64_t static_value2 = 0x07508b9011bd9a1aULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drrobot_clinicrobot/BumpSensor";
  }

  static const char* value(const ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Bump Sensor information message from DrRobot Robot.\n\
\n\
Header header    	# timestamp in the header is the time\n\
uint8 bump_sw1		# middle_right\n\
uint8 bump_sw2		# right\n\
uint8 bump_sw3		# middle_left\n\
uint8 bump_sw4		# left\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bump_sw1);
      stream.next(m.bump_sw2);
      stream.next(m.bump_sw3);
      stream.next(m.bump_sw4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BumpSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drrobot_clinicrobot::BumpSensor_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bump_sw1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bump_sw1);
    s << indent << "bump_sw2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bump_sw2);
    s << indent << "bump_sw3: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bump_sw3);
    s << indent << "bump_sw4: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bump_sw4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRROBOT_CLINICROBOT_MESSAGE_BUMPSENSOR_H
