// Generated by gencpp from file drrobot_clinicrobot/IndoorGPS.msg
// DO NOT EDIT!


#ifndef DRROBOT_CLINICROBOT_MESSAGE_INDOORGPS_H
#define DRROBOT_CLINICROBOT_MESSAGE_INDOORGPS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace drrobot_clinicrobot
{
template <class ContainerAllocator>
struct IndoorGPS_
{
  typedef IndoorGPS_<ContainerAllocator> Type;

  IndoorGPS_()
    : header()
    , robot_x(0.0)
    , robot_y(0.0)
    , robot_heading(0.0)
    , markid_height(0.0)
    , mark_id(0)
    , valid_flag(0)  {
    }
  IndoorGPS_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_x(0.0)
    , robot_y(0.0)
    , robot_heading(0.0)
    , markid_height(0.0)
    , mark_id(0)
    , valid_flag(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _robot_x_type;
  _robot_x_type robot_x;

   typedef float _robot_y_type;
  _robot_y_type robot_y;

   typedef float _robot_heading_type;
  _robot_heading_type robot_heading;

   typedef float _markid_height_type;
  _markid_height_type markid_height;

   typedef uint32_t _mark_id_type;
  _mark_id_type mark_id;

   typedef uint8_t _valid_flag_type;
  _valid_flag_type valid_flag;




  typedef boost::shared_ptr< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> const> ConstPtr;

}; // struct IndoorGPS_

typedef ::drrobot_clinicrobot::IndoorGPS_<std::allocator<void> > IndoorGPS;

typedef boost::shared_ptr< ::drrobot_clinicrobot::IndoorGPS > IndoorGPSPtr;
typedef boost::shared_ptr< ::drrobot_clinicrobot::IndoorGPS const> IndoorGPSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drrobot_clinicrobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'drrobot_clinicrobot': ['/home/drrobot2/hokuyo_exp/src/drrobot_clinicrobot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "28c7106d8f3f5a0bd38a8f7719376e0a";
  }

  static const char* value(const ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x28c7106d8f3f5a0bULL;
  static const uint64_t static_value2 = 0xd38a8f7719376e0aULL;
};

template<class ContainerAllocator>
struct DataType< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drrobot_clinicrobot/IndoorGPS";
  }

  static const char* value(const ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# InDoor GPS Sensor information message from DrRobot Robot.\n\
\n\
Header header    	# timestamp in the header is the time the \n\
\n\
#make sure below sensors on your robot or not\n\
float32 robot_x	# robot x position reading\n\
float32 robot_y	#robot y position reading\n\
float32 robot_heading	# robot heading reading\n\
float32 markid_height	# mark height\n\
uint32 mark_id		# mark ID\n\
uint8 valid_flag	# valid or not, 0- in dead zone, no reading\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_x);
      stream.next(m.robot_y);
      stream.next(m.robot_heading);
      stream.next(m.markid_height);
      stream.next(m.mark_id);
      stream.next(m.valid_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct IndoorGPS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drrobot_clinicrobot::IndoorGPS_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_x: ";
    Printer<float>::stream(s, indent + "  ", v.robot_x);
    s << indent << "robot_y: ";
    Printer<float>::stream(s, indent + "  ", v.robot_y);
    s << indent << "robot_heading: ";
    Printer<float>::stream(s, indent + "  ", v.robot_heading);
    s << indent << "markid_height: ";
    Printer<float>::stream(s, indent + "  ", v.markid_height);
    s << indent << "mark_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mark_id);
    s << indent << "valid_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRROBOT_CLINICROBOT_MESSAGE_INDOORGPS_H
