(cl:in-package drrobot_clinicrobot-msg)
(cl:export '(HEADER-VAL
          HEADER
          SYSTEM_VOL-VAL
          SYSTEM_VOL
          CHARGESTATION_FLAG-VAL
          CHARGESTATION_FLAG
          CHARGE_FLAG-VAL
          CHARGE_FLAG
          MOTIONBOARD_VOL-VAL
          MOTIONBOARD_VOL
          ROBOT_X-VAL
          ROBOT_X
          ROBOT_Y-VAL
          ROBOT_Y
          ROBOT_HEADING-VAL
          ROBOT_HEADING
          HEAD_TILTANGLE-VAL
          HEAD_TILTANGLE
          HEAD_PANANGLE-VAL
          HEAD_PANANGLE
          LASER_TILTANGLE-VAL
          LASER_TILTANGLE
          BUMPSENSOR-VAL
          BUMPSENSOR
          FACEIMAGE_NUM-VAL
          FACEIMAGE_NUM
          POWER_SOURCE-VAL
          POWER_SOURCE
))