(cl:in-package drrobot_clinicrobot-msg)
(cl:export '(HEADER-VAL
          HEADER
          BATTERY_VOL-VAL
          BATTERY_VOL
          SYSTEM_VOL-VAL
          SYSTEM_VOL
          BATTERY_FUEL-VAL
          BATTERY_FUEL
          DCIN_VOL-VAL
          DCIN_VOL
          DCIN_CURRENT-VAL
          DCIN_CURRENT
          CHARGE_TIME_MIN-VAL
          CHARGE_TIME_MIN
          CHARGE_TIME_SEC-VAL
          CHARGE_TIME_SEC
          CHARGE_ERROR_CODE-VAL
          CHARGE_ERROR_CODE
          CHARGE_MODE-VAL
          CHARGE_MODE
          CHARGE_STATUS-VAL
          CHARGE_STATUS
          CHARGE_RX_STATUS-VAL
          CHARGE_RX_STATUS
          CHARGER_TEMPERATURE-VAL
          CHARGER_TEMPERATURE
          SET_CHARGE_CURRENT-VAL
          SET_CHARGE_CURRENT
          CHARGE_FLAG-VAL
          CHARGE_FLAG
          IN_CHARGESTATION_FLAG-VAL
          IN_CHARGESTATION_FLAG
          CELL_VOL-VAL
          CELL_VOL
          CELL_RES-VAL
          CELL_RES
))